2025-01-08 16:22:55,303 INFO    MainThread:54736 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-01-08 16:22:55,304 INFO    MainThread:54736 [wandb_setup.py:_flush():68] Configure stats pid to 54736
2025-01-08 16:22:55,304 INFO    MainThread:54736 [wandb_setup.py:_flush():68] Loading settings from C:\Users\jimal\.config\wandb\settings
2025-01-08 16:22:55,304 INFO    MainThread:54736 [wandb_setup.py:_flush():68] Loading settings from C:\Users\jimal\OneDrive - BUas\Desktop\Block_2B\Y2B-2023-OT2_Twin\wandb\settings
2025-01-08 16:22:55,304 INFO    MainThread:54736 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-08 16:22:55,304 INFO    MainThread:54736 [wandb_init.py:_log_setup():528] Logging user logs to C:\Users\jimal\OneDrive - BUas\Desktop\Block_2B\Y2B-2023-OT2_Twin\wandb\run-20250108_162255-3n7kslbr\logs\debug.log
2025-01-08 16:22:55,305 INFO    MainThread:54736 [wandb_init.py:_log_setup():529] Logging internal logs to C:\Users\jimal\OneDrive - BUas\Desktop\Block_2B\Y2B-2023-OT2_Twin\wandb\run-20250108_162255-3n7kslbr\logs\debug-internal.log
2025-01-08 16:22:55,306 INFO    MainThread:54736 [wandb_init.py:init():644] calling init triggers
2025-01-08 16:22:55,306 INFO    MainThread:54736 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {}
2025-01-08 16:22:55,306 INFO    MainThread:54736 [wandb_init.py:init():680] starting backend
2025-01-08 16:22:55,306 INFO    MainThread:54736 [wandb_init.py:init():684] sending inform_init request
2025-01-08 16:22:55,423 INFO    MainThread:54736 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-01-08 16:22:55,424 INFO    MainThread:54736 [wandb_init.py:init():697] backend started and connected
2025-01-08 16:22:55,427 INFO    MainThread:54736 [wandb_init.py:init():790] updated telemetry
2025-01-08 16:22:55,567 INFO    MainThread:54736 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-01-08 16:24:26,570 ERROR   MainThread:54736 [wandb_init.py:init():849] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-08 16:24:26,570 ERROR   MainThread:54736 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\jimal\anaconda3\envs\Y2B\lib\site-packages\wandb\sdk\wandb_init.py", line 1298, in init
    return wi.init()
  File "C:\Users\jimal\anaconda3\envs\Y2B\lib\site-packages\wandb\sdk\wandb_init.py", line 855, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-08 16:24:26,607 WARNING MsgRouterThr:54736 [router.py:message_loop():75] message_loop has been closed
